/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Address information
 */
export interface AddressDto { 
    /**
     * Street address
     */
    street: string;
    /**
     * City
     */
    city: string;
    /**
     * State or province
     */
    state: string;
    /**
     * Postal/Zip code
     */
    zipCode: string;
}

