/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Authentication request containing username and password.
 */
export interface AuthRequest { 
    /**
     * User\'s login name
     */
    username?: string;
    /**
     * User\'s password
     */
    password?: string;
}

