/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Contact information
 */
export interface ContactInformationDto { 
    /**
     * Phone number
     */
    phoneNumber: string;
    /**
     * Email address
     */
    email: string;
}

