/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Emergency contact information
 */
export interface EmergencyContactDto { 
    /**
     * Emergency contact\'s first name
     */
    firstName: string;
    /**
     * Emergency contact\'s last name
     */
    lastName: string;
    /**
     * Emergency contact\'s phone number
     */
    phoneNumber: string;
}

