/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmployeeCreateDto } from './employeeCreateDto';


/**
 * User registration request
 */
export interface RegisterRequest { 
    /**
     * Unique username for the account
     */
    username: string;
    /**
     * User\'s email address
     */
    email: string;
    /**
     * User\'s password
     */
    password: string;
    /**
     * User role
     */
    role: RegisterRequest.RoleEnum;
    employeeCreateDto: EmployeeCreateDto;
}
export namespace RegisterRequest {
    export const RoleEnum = {
        User: 'USER',
        Admin: 'ADMIN',
        Manager: 'MANAGER'
    } as const;
    export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];
}


