/**
 * Employee Service API
 *
 * Contact: support@employee-service.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Employee summary information
 */
export interface EmployeeList { 
    /**
     * Employee\'s id
     */
    id?: string;
    /**
     * Employee\'s first name
     */
    firstName?: string;
    /**
     * Employee\'s middle name
     */
    middleName?: string | null;
    /**
     * Employee\'s last name
     */
    lastName?: string;
    /**
     * Employee\'s job title
     */
    jobTitle?: string;
    /**
     * URL of employee\'s profile image
     */
    imageUrl?: string | null;
}

