/**
 * Employee Service API
 *
 * Contact: support@employee-service.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SortObject } from './sortObject';


export interface PageableObject { 
    pageNumber?: number;
    pageSize?: number;
    offset?: number;
    sort?: Array<SortObject>;
    paged?: boolean;
    unpaged?: boolean;
}

