/**
 * Employee Service API
 *
 * Contact: support@employee-service.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageableObject } from './pageableObject';
import { SortObject } from './sortObject';
import { EmployeeList } from './employeeList';


export interface PageEmployeeList { 
    totalPages?: number;
    totalElements?: number;
    numberOfElements?: number;
    pageable?: PageableObject;
    first?: boolean;
    last?: boolean;
    size?: number;
    content?: Array<EmployeeList>;
    number?: number;
    sort?: Array<SortObject>;
    empty?: boolean;
}

